// Automatically generated using enum_gen.py

#include "ap/items.h"

ap_item_type_t ap_item_type(ap_item_t item) {
  switch (item) {
    case AP_ITEM_CORNERIA_CHECKPOINT: return AP_ITEM_TYPE_CHECKPOINT;
    case AP_ITEM_METEO_CHECKPOINT: return AP_ITEM_TYPE_CHECKPOINT;
    case AP_ITEM_SECTOR_X_CHECKPOINT: return AP_ITEM_TYPE_CHECKPOINT;
    case AP_ITEM_TITANIA_CHECKPOINT: return AP_ITEM_TYPE_CHECKPOINT;
    case AP_ITEM_SECTOR_Y_CHECKPOINT: return AP_ITEM_TYPE_CHECKPOINT;
    case AP_ITEM_AQUAS_CHECKPOINT: return AP_ITEM_TYPE_CHECKPOINT;
    case AP_ITEM_ZONESS_CHECKPOINT: return AP_ITEM_TYPE_CHECKPOINT;
    case AP_ITEM_AREA_6_CHECKPOINT: return AP_ITEM_TYPE_CHECKPOINT;
    case AP_ITEM_SOLAR_CHECKPOINT: return AP_ITEM_TYPE_CHECKPOINT;
    case AP_ITEM_MACBETH_CHECKPOINT: return AP_ITEM_TYPE_CHECKPOINT;
    case AP_ITEM_VENOM_1_CHECKPOINT: return AP_ITEM_TYPE_CHECKPOINT;
    case AP_ITEM_AQUAS_RED_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_AREA_6_RED_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_BOLSE_BLUE_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_CORNERIA_BLUE_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_CORNERIA_RED_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_FORTUNA_BLUE_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_FORTUNA_YELLOW_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_KATINA_BLUE_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_KATINA_YELLOW_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_MACBETH_BLUE_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_MACBETH_RED_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_METEO_BLUE_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_METEO_WARP_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_SECTOR_X_BLUE_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_SECTOR_X_YELLOW_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_SECTOR_X_WARP_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_SECTOR_Y_YELLOW_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_SECTOR_Y_RED_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_SECTOR_Z_BLUE_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_SECTOR_Z_RED_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_SOLAR_YELLOW_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_TITANIA_BLUE_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_ZONESS_YELLOW_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_ZONESS_RED_PATH: return AP_ITEM_TYPE_PATH;
    case AP_ITEM_DEFEATED_ROBOT_ANDROSS: return AP_ITEM_TYPE_EVENT;
    case AP_ITEM_DEFEATED_ANDROSS: return AP_ITEM_TYPE_EVENT;
    default: return AP_ITEM_TYPE_NONE;
  }
}
