#pragma once

// Automatically generated using enum_gen.py

typedef enum {
  AP_OPTION_DEATHLINK = 0,
  AP_OPTION_VICTORY_CONDITION = 1,
  AP_OPTION_REQUIRED_MEDALS = 2,
  AP_OPTION_SHUFFLE_MEDALS = 3,
  AP_OPTION_SHUFFLE_PATHS = 4,
  AP_OPTION_ACCOMPLISHED_SENDS_COMPLETE = 5,
  AP_OPTION_RADIO_RANDO = 6,
  AP_OPTION_DEFAULT_LIVES = 7,
  AP_OPTION_MEDAL_CORNERIA = 8,
  AP_OPTION_MEDAL_METEO = 9,
  AP_OPTION_MEDAL_SECTOR_Y = 10,
  AP_OPTION_MEDAL_KATINA = 11,
  AP_OPTION_MEDAL_FORTUNA = 12,
  AP_OPTION_MEDAL_AQUAS = 13,
  AP_OPTION_MEDAL_SOLAR = 14,
  AP_OPTION_MEDAL_SECTOR_X = 15,
  AP_OPTION_MEDAL_ZONESS = 16,
  AP_OPTION_MEDAL_TITANIA = 17,
  AP_OPTION_MEDAL_SECTOR_Z = 18,
  AP_OPTION_MEDAL_MACBETH = 19,
  AP_OPTION_MEDAL_AREA_6 = 20,
  AP_OPTION_MEDAL_BOLSE = 21,
  AP_OPTION_MEDAL_VENOM = 22,
  AP_OPTION_RINGLINK = 23,
  AP_OPTION_MAX = 24,
} ap_option_t;

typedef enum {
  AP_OPTION_VICTORY_CONDITION_ANDROSS_OR_ROBOT_ANDROSS = 0,
  AP_OPTION_VICTORY_CONDITION_ANDROSS_AND_ROBOT_ANDROSS = 1,
  AP_OPTION_VICTORY_CONDITION_ANDROSS = 2,
  AP_OPTION_VICTORY_CONDITION_MAX = 3,
} ap_option_victory_condition_t;
