#pragma once

// Automatically generated using enum_gen.py

typedef enum {
  AP_OPTION_DEATHLINK = 0,
  AP_OPTION_RINGLINK = 1,
  AP_OPTION_VICTORY_CONDITION = 2,
  AP_OPTION_REQUIRED_MEDALS = 3,
  AP_OPTION_SHUFFLE_MEDALS = 4,
  AP_OPTION_SHUFFLE_PATHS = 5,
  AP_OPTION_SHUFFLE_CHECKPOINTS = 6,
  AP_OPTION_ACCOMPLISHED_SENDS_COMPLETE = 7,
  AP_OPTION_RADIO_RANDO = 8,
  AP_OPTION_DEFAULT_LIVES = 9,
  AP_OPTION_MEDAL_CORNERIA = 10,
  AP_OPTION_MEDAL_METEO = 11,
  AP_OPTION_MEDAL_SECTOR_Y = 12,
  AP_OPTION_MEDAL_KATINA = 13,
  AP_OPTION_MEDAL_FORTUNA = 14,
  AP_OPTION_MEDAL_AQUAS = 15,
  AP_OPTION_MEDAL_SOLAR = 16,
  AP_OPTION_MEDAL_SECTOR_X = 17,
  AP_OPTION_MEDAL_ZONESS = 18,
  AP_OPTION_MEDAL_TITANIA = 19,
  AP_OPTION_MEDAL_SECTOR_Z = 20,
  AP_OPTION_MEDAL_MACBETH = 21,
  AP_OPTION_MEDAL_AREA_6 = 22,
  AP_OPTION_MEDAL_BOLSE = 23,
  AP_OPTION_MEDAL_VENOM = 24,
  AP_OPTION_MAX = 25,
} ap_option_t;

typedef enum {
  AP_OPTION_VICTORY_CONDITION_ANDROSS_OR_ROBOT_ANDROSS = 0,
  AP_OPTION_VICTORY_CONDITION_ANDROSS_AND_ROBOT_ANDROSS = 1,
  AP_OPTION_VICTORY_CONDITION_ANDROSS = 2,
  AP_OPTION_VICTORY_CONDITION_MAX = 3,
} ap_option_victory_condition_t;

typedef enum {
  AP_OPTION_RADIO_RANDO_OFF = 0,
  AP_OPTION_RADIO_RANDO_ON = 1,
  AP_OPTION_RADIO_RANDO_ON_INCLUDING_TRAINING = 2,
  AP_OPTION_RADIO_RANDO_MAX = 3,
} ap_option_radio_rando_t;
