# Automatically generated using enum_gen.py

option_name_to_id = {
  "deathlink": 0,
  "ringlink": 1,
  "victory_condition": 2,
  "required_medals": 3,
  "shuffle_medals": 4,
  "shuffle_paths": 5,
  "shuffle_checkpoints": 6,
  "accomplished_sends_complete": 7,
  "radio_rando": 8,
  "engine_glow": 9,
  "default_lives": 10,
  "medal_corneria": 11,
  "medal_meteo": 12,
  "medal_sector_y": 13,
  "medal_katina": 14,
  "medal_fortuna": 15,
  "medal_aquas": 16,
  "medal_solar": 17,
  "medal_sector_x": 18,
  "medal_zoness": 19,
  "medal_titania": 20,
  "medal_sector_z": 21,
  "medal_macbeth": 22,
  "medal_area_6": 23,
  "medal_bolse": 24,
  "medal_venom": 25
}

item_name_to_id = {
  "None": -1,
  "Nothing": 1,
  "Laser Upgrade": 2,
  "Silver Ring": 3,
  "Silver Star": 4,
  "Gold Ring": 5,
  "Bomb": 6,
  "Extra Arwing": 7,
  "Medal": 8,
  "Corneria - Checkpoint": 9,
  "Meteo - Checkpoint": 10,
  "Sector X - Checkpoint": 11,
  "Titania - Checkpoint": 12,
  "Sector Y - Checkpoint": 13,
  "Aquas - Checkpoint": 14,
  "Zoness - Checkpoint": 15,
  "Area 6 - Checkpoint": 16,
  "Solar - Checkpoint": 17,
  "Macbeth - Checkpoint": 18,
  "Venom 1 - Checkpoint": 19,
  "Aquas - Red Path": 20,
  "Area 6 - Red Path": 21,
  "Bolse - Blue Path": 22,
  "Corneria - Blue Path": 23,
  "Corneria - Red Path": 24,
  "Fortuna - Blue Path": 25,
  "Fortuna - Yellow Path": 26,
  "Katina - Blue Path": 27,
  "Katina - Yellow Path": 28,
  "Macbeth - Blue Path": 29,
  "Macbeth - Red Path": 30,
  "Meteo - Blue Path": 31,
  "Meteo - Warp Path": 32,
  "Sector X - Blue Path": 33,
  "Sector X - Yellow Path": 34,
  "Sector X - Warp Path": 35,
  "Sector Y - Yellow Path": 36,
  "Sector Y - Red Path": 37,
  "Sector Z - Blue Path": 38,
  "Sector Z - Red Path": 39,
  "Solar - Yellow Path": 40,
  "Titania - Blue Path": 41,
  "Zoness - Yellow Path": 42,
  "Zoness - Red Path": 43,
  "Defeated Robot Andross": 44,
  "Defeated Andross": 45
}

location_name_to_id = {
  "None": -1,
  "Goal Completed": 0,
  "Aquas - Mission Complete": 1,
  "Aquas - Medal": 2,
  "Aquas - Checkpoint": 3,
  "Area 6 - Mission Complete": 4,
  "Area 6 - Medal": 5,
  "Area 6 - Below Early Defense Station: Gold Ring": 6,
  "Area 6 - Above Early Defense Station: Laser Upgrade": 7,
  "Area 6 - Andross' Taunt: Gold Ring": 8,
  "Area 6 - Checkpoint": 9,
  "Area 6 - Near Defense Station After Checkpoint: Gold Ring": 10,
  "Bolse - Mission Complete": 11,
  "Bolse - Medal": 12,
  "Corneria - Mission Complete": 13,
  "Corneria - Mission Accomplished": 14,
  "Corneria - Medal": 15,
  "Corneria - Under Arch: Gold Ring": 16,
  "Corneria - Behind Doors: Bomb": 17,
  "Corneria - Center Of Corneria City: Silver Ring": 18,
  "Corneria - Near First Ground Robot: Laser Upgrade": 19,
  "Corneria - Under Highway Arch: Gold Ring": 20,
  "Corneria - Behind Second Ground Robot: Bomb": 21,
  "Corneria - Behind Doors Near Checkpoint: Gold Ring": 22,
  "Corneria - Checkpoint": 23,
  "Corneria - After Falco's G-Diffuser Issue: Laser Upgrade": 24,
  "Corneria - After Falco's G-Diffuser Issue: Bomb": 25,
  "Corneria - Water Section Last Arch: Gold Ring": 26,
  "Corneria - Left Of Waterfall: Laser Upgrade": 27,
  "Corneria - Before Mission Complete Boss, Lower: Gold Ring": 28,
  "Corneria - Before Mission Complete Boss, Upper: Gold Ring": 29,
  "Fortuna - Mission Complete": 30,
  "Fortuna - Mission Accomplished": 31,
  "Fortuna - Medal": 32,
  "Katina - Mission Complete": 33,
  "Katina - Mission Accomplished": 34,
  "Katina - Medal": 35,
  "Macbeth - Mission Complete": 36,
  "Macbeth - Mission Accomplished": 37,
  "Macbeth - Medal": 38,
  "Macbeth - Before Hill With Rolling Rocks: Bomb": 39,
  "Macbeth - Above Rolling Rocks: Gold Ring": 40,
  "Macbeth - On Tracks Before Bridge: Gold Ring": 41,
  "Macbeth - On Tracks After Bridge: Gold Ring": 42,
  "Macbeth - Checkpoint": 43,
  "Macbeth - After First Building: Silver Ring": 44,
  "Macbeth - Before Buildings Three And Four: Silver Ring": 45,
  "Macbeth - After Buildings Three And Four, Right: Silver Ring": 46,
  "Macbeth - Before Building Five: Silver Ring": 47,
  "Macbeth - After Building Five: Gold Ring": 48,
  "Macbeth - Under Bridge After Checkpoint: Bomb": 49,
  "Macbeth - First Building After Switcher: Gold Ring": 50,
  "Macbeth - Second Building After Switcher: Silver Ring": 51,
  "Macbeth - After Marker 100: Silver Ring": 52,
  "Macbeth - Before Marker 300: Silver Ring": 53,
  "Meteo - Mission Complete": 54,
  "Meteo - Warp": 55,
  "Meteo - Medal": 56,
  "Meteo - After Starting Asteroids: Gold Ring": 57,
  "Meteo - End Of First Tunnel, Top: Gold Ring": 58,
  "Meteo - End Of First Tunnel, Middle: Silver Ring": 59,
  "Meteo - End Of First Tunnel, Bottom: Bomb": 60,
  "Meteo - Between Two Big Asteroids: Bomb": 61,
  "Meteo - Checkpoint": 62,
  "Meteo - Near Warp Rings: Gold Ring": 63,
  "Meteo - Just Before Boss: Gold Ring": 64,
  "Sector X - Mission Complete": 65,
  "Sector X - Mission Accomplished": 66,
  "Sector X - Warp": 67,
  "Sector X - Medal": 68,
  "Sector X - In Debris Field, Left: Gold Ring": 69,
  "Sector X - Checkpoint": 70,
  "Sector X - Behind Enemy After Peppy Gets Chased, Right: Gold Ring": 71,
  "Sector X - Left Path - Just After Fork, Through Bottom Slot: Laser Upgrade": 72,
  "Sector X - Left Path - Closing Door Section: Gold Ring": 73,
  "Sector X - Left Path - After Closing Door Section: Bomb": 74,
  "Sector X - Left Path - Behind First Warp Gate: Gold Ring": 75,
  "Sector X - Left Path - After First Warp Gate, Up High: Bomb": 76,
  "Sector X - Left Path - Before Final Warp Gate: Gold Ring": 77,
  "Sector Y - Mission Complete": 78,
  "Sector Y - Mission Accomplished": 79,
  "Sector Y - Medal": 80,
  "Sector Y - Above Friendly Ship Near Start: Gold Ring": 81,
  "Sector Y - Before Checkpoint: Gold Ring": 82,
  "Sector Y - Checkpoint": 83,
  "Sector Y - Breaking Through The Enemy Fleet, Beginning: Gold Ring": 84,
  "Sector Y - Breaking Through The Enemy Fleet, Middle: Gold Ring": 85,
  "Sector Y - Breaking Through The Enemy Fleet, End: Gold Ring": 86,
  "Sector Z - Mission Complete": 87,
  "Sector Z - Mission Accomplished": 88,
  "Sector Z - Medal": 89,
  "Solar - Mission Complete": 90,
  "Solar - Medal": 91,
  "Solar - Checkpoint": 92,
  "Titania - Mission Complete": 93,
  "Titania - Medal": 94,
  "Titania - Second Falling Tower From Start: Bomb": 95,
  "Titania - Through Two Leaning Towers: Gold Ring": 96,
  "Titania - After Three Bone Structures: Bomb": 97,
  "Titania - Above Skull: Silver Ring": 98,
  "Titania - On Bridge: Gold Ring": 99,
  "Titania - Right Of Bridge: Gold Ring": 100,
  "Titania - Upper Left Path: Bomb": 101,
  "Titania - Suspended Above Two Bridges: Silver Ring": 102,
  "Titania - Checkpoint": 103,
  "Titania - Falling Towers Section: First Bomb": 104,
  "Titania - Falling Towers Section: Gold Ring": 105,
  "Titania - Falling Towers Section: Second Bomb": 106,
  "Titania - Falling Towers Section: Third Bomb": 107,
  "Titania - Behind Arches On The Right: Gold Ring": 108,
  "Titania - Upper Right Hill: Gold Ring": 109,
  "Titania - First Falling Tower Before Boss: Silver Ring": 110,
  "Titania - First Falling Tower Before Boss: Gold Ring": 111,
  "Titania - Second Falling Tower Before Boss: Silver Ring": 112,
  "Titania - Second Falling Tower Before Boss: Gold Ring": 113,
  "Venom - Medal": 114,
  "Venom - Defeat Robot Andross": 115,
  "Venom 1 - Near Start, Bottom: Gold Ring": 116,
  "Venom 1 - Near Start, Top: Laser Upgrade": 117,
  "Venom 1 - Maze (R R R): Gold Ring": 118,
  "Venom 1 - Maze (L L): Gold Ring": 119,
  "Venom 1 - Maze (R R L L): Gold Ring": 120,
  "Venom 1 - End Of Maze (R R R R): Gold Ring": 121,
  "Venom 1 - End Of Maze (L L L): Gold Ring": 122,
  "Venom 1 - End Of Maze (R R L L): Gold Ring": 123,
  "Venom 1 - Checkpoint": 124,
  "Venom - Defeat Andross": 125,
  "Zoness - Mission Complete": 126,
  "Zoness - Mission Accomplished": 127,
  "Zoness - Medal": 128,
  "Zoness - Before Katt Appears, Top: Gold Ring": 129,
  "Zoness - Before Katt Appears, Middle: Silver Ring": 130,
  "Zoness - Before Katt Appears, Bottom: Bomb": 131,
  "Zoness - Checkpoint": 132,
  "Zoness - Aim For The Rudder, First Gate: Laser Upgrade": 133,
  "Zoness - Aim For The Rudder, Second Gate, Left: Bomb": 134,
  "Zoness - Aim For The Rudder, Third Gate: Silver Ring": 135
}

class AP_CMD:
  NONE = 0
  HANDSHAKE = 1
  PING = 2
  PONG = 3
  SEED = 4
  OPTIONS = 5
  READY = 6
  LOCATIONS = 7
  ITEMS = 8
  DEATHLINK = 9
  RINGLINK = 10
  MESSAGE = 11

class AP_STATE:
  DISCONNECTED = 0
  CONNECTING = 1
  CONNECTED = 2
  PINGED = 4
